## Student Performance Prediction

### Importing necessary libraries

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.

### Reading file

In [2]:
df = pd.read_csv("data/stud.csv")

In [3]:
df.head(5)

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

### Checking null values

In [4]:
df.isnull().sum()

gender                         0
race_ethnicity                 0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
dtype: int64

### Observation: No null values present in the dataset

### Getting shape

In [5]:
shape = df.shape 
print(f"Number of rows in the dataset are : {shape[0]}")
print(f"Number of columns in the dataset are : {shape[1]}")

Number of rows in the dataset are : 1000
Number of columns in the dataset are : 8

### Checking duplicate values

In [6]:
df.duplicated().sum()

np.int64(0)

### Getting statistical info

In [7]:
df.describe()

       math_score  reading_score  writing_score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

### Creating two new features "Total score" and "Average score"

In [8]:
df["total_score"] = df["math_score"]+df["reading_score"]+df["writing_score"]
df["average"] = df["total_score"]/3
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,total_score,average
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667
1,female,group C,some college,standard,completed,69,90,88,247,82.333333
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333
4,male,group C,some college,standard,none,76,78,75,229,76.333333

### Getting number of students scoring full marks

In [9]:
maths = df[df["math_score"]==100]["average"].count()
reading = df[df["reading_score"]==100]["average"].count()
writing = df[df["writing_score"]==100]["average"].count()

print(f"Number of students getting full marks in maths are : {maths}")
print(f"Number of students getting full marks in reading are : {reading}")
print(f"Number of students getting full marks in writing are : {writing}")

Number of students getting full marks in maths are : 7
Number of students getting full marks in reading are : 17
Number of students getting full marks in writing are : 14

### Observation: Best performance is in reading

### Getting number of students performing poorly

In [10]:
maths = df[df["math_score"]<=20]["average"].count()
reading = df[df["reading_score"]<=20]["average"].count()
writing = df[df["writing_score"]<=20]["average"].count()

print(f"Number of students getting less marks in maths are : {maths}")
print(f"Number of students getting less marks in reading are : {reading}")
print(f"Number of students getting less marks in writing are : {writing}")

Number of students getting less marks in maths are : 4
Number of students getting less marks in reading are : 1
Number of students getting less marks in writing are : 3

### Observation: Worst performance is in maths

### Getting unique values

In [11]:
df.nunique()

gender                           2
race_ethnicity                   5
parental_level_of_education      6
lunch                            2
test_preparation_course          2
math_score                      81
reading_score                   72
writing_score                   77
total_score                    194
average                        194
dtype: int64

In [19]:
print(f"Unique values in gender are :",end=" ")
print(df["gender"].unique().tolist())

print(f"Unique values in race_ethnicity are :",end=" ")
print(df["race_ethnicity"].unique().tolist())

print(f"Unique values in parental_level_of_education are :",end=" ")
print(df["parental_level_of_education"].unique().tolist())

print(f"Unique values in lunch are :",end=" ")
print(df["lunch"].unique().tolist())

print(f"Unique values in test_preparation_course are :",end=" ")
print(df["test_preparation_course"].unique().tolist())

Unique values in gender are : ['female', 'male']
Unique values in race_ethnicity are : ['group B', 'group C', 'group A', 'group D', 'group E']
Unique values in parental_level_of_education are : ["bachelor's degree", 'some college', "master's degree", "associate's degree", 'high school', 'some high school']
Unique values in lunch are : ['standard', 'free/reduced']
Unique values in test_preparation_course are : ['none', 'completed']

### Getting categorical and numerical features

In [24]:
num_features = [feature for feature in df.columns if df[feature].dtype!="str"]
cat_features = [feature for feature in df.columns if df[feature].dtype=="str"]

print(f"There are {len(num_features)} numerical features named {num_features}")
print(f"There are {len(cat_features)} categorical featres named {cat_features}")

There are 5 numerical features named ['math_score', 'reading_score', 'writing_score', 'total_score', 'average']
There are 5 categorical featres named ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race_ethnicity               1000 non-null   str
 2   parental_level_of_education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test_preparation_course      1000 non-null   str
 5   math_score                   1000 non-null   int64
 6   reading_score                1000 non-null   int64
 7   writing_score                1000 non-null   int64
 8   total_score                  1000 non-null   int64
 9   average                      1000 non-null   float64
dtypes: float64(1), int64(4), str(5)
memory usage: 78.3 KB